### ISSUE TITLE
Flow cannot assign apex method's output value as expected

### ISSUE THREAD

**Issue by sungysang** [lovinghouston/lwcgoogleplacesbutton#10]
The invocable apex method can be called in the flow and find related records (per debug logs), but currently the output cannot be assigned to a record collection variable. According to [this forum post](https://developer.salesforce.com/forums/?id=906F00000005GQdIAM), the method should actually return a List of Lists rather than a List.

**Comment by Julian88Tex** [comment]
@sungysang Thanks for doing this research. It sounds like this issue instead should be a comment on Issue #2 and that we need to update the ACs of this issue. I'm not sure I quite understand, mind rephrasing as a comment on that issue and closing this one out (unless you think this shouldn't be added to issue #2) with a bit more layman's terms explanation of what can and cannot be done with the current ACs. Also if you have a recommendation of what we can do and how we should update them, feel free to go ahead and update ACs. Thanks!

**Comment by sungysang** [comment]
@Julian88Tex Yeah this should actually be a part of #2.
