### ISSUE TITLE
Create Unit Tests

### ISSUE THREAD

**Issue by sungysang** [lovinghouston/lwcgoogleplacesbutton#11]

**Comment by sungysang** [comment]
@Julian88Tex Mind adding some good tests I can write in?

**Comment by Julian88Tex** [comment]
@sungysang can you clarify? You want me to write tests or you just want me to write the things to test and you’ll code them?

**Comment by Julian88Tex** [comment]
@sungysang In either case usually Unit Tests are implied by any code being written. I'd recommend we add those as ACs to a given ticket if you'd like to have them on there. That being said, are the current ACs not detailed enough? If so, please comment on that ticket quoting an AC as an example and I can work on adding more context.

**Comment by sungysang** [comment]
@Julian88Tex yeah I was thinking specifically scenarios that I can code out but they're already in Issues 1-4 ... sorry it's late!

**Comment by Julian88Tex** [comment]
@sungysang all good! Glad you're having fun with working on this :-)
