### ISSUE TITLE
Display Google Places Data on Lightning Data Table

### ISSUE THREAD

**Issue by Julian88Tex** [lovinghouston/lwcgoogleplacesbutton#13]
As a user, I would like to be able to see the first 10 Google Places Search data in a lightning component based on that Account's zip code and type.

LDS Data Table: https://www.lightningdesignsystem.com/components/data-tables/#Actionable-mode-Column-sorting-and-row-selection(s)

Documentation: https://developers.google.com/places/web-service/search#PlaceSearchRequests

Given an Account exists
And I have added the "Account Search" LWC to my page layout
And the Account has a Zip Code
When I view an Account record
Then I will see 10 places
And they will have a type = church attribute
And they will be selectable

Notes: 

Potential Idea: Use JSON.serialize to send a List of Objects with the important values from the call.

Data Schema:
List --> Map<String,String> (Each Map is a record that's housed in the List of Objects)
[
{Church_Account__c: "0015400000Tc4GKAAZ", School_Account__c: "0015400000SYBvyAAH", Status__c: "Potential", Id: "a0k54000009MotrAAC"}
]
https://foobarforce.wordpress.com/2014/07/25/apex-method-of-the-day-json-serialize-object/

After the rows are selected, pass the {selectedRows} back to an Apex method that will then perform DML operations.

**Comment by sungysang** [comment]
@Julian88Tex is this one okay to close?

**Comment by Julian88Tex** [comment]
@sungysang yup thanks
