### ISSUE TITLE
Spike: Learn how to Encrypt Google API Key with Github Secrets

### ISSUE THREAD

**Issue by sungysang** [lovinghouston/lwcgoogleplacesbutton#15]

**Comment by Julian88Tex** [comment]
@sungysang some documentation: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets

So I don't think you can extract the secret when you let's say clone or pull from the repo... it's more for CICD tools I think. So it's probably best to just share the key with us in LastPass. I did that previously for an old version of the key and will do it now.

**Comment by Julian88Tex** [comment]
@sungysang @mersine y'all should both have an email from LastPass that will allow you to access the key

**Comment by Julian88Tex** [comment]
@sungysang @mersine can y'all confirm that you can see the key in LastPass by commenting on this ticket?

**Comment by rodney-zhu** [comment]
I have the key in Lastpass now. @Julian88Tex

**Comment by Julian88Tex** [comment]
@Rodney-Zhu great!

**Comment by Julian88Tex** [comment]
@sungysang closing since this ticket doesn't really make sense. We wouldn't store the key in github unless we were doing CI/CD which we aren't for now.
