### ISSUE TITLE
Spike: Learn Agile/Scrum Best Practices

### ISSUE THREAD

**Issue by Julian88Tex** [lovinghouston/lwcgoogleplacesbutton#16]
@mersine Made this Trailmix for you on agile/scrum: https://trailhead.salesforce.com/en/users/julianjoseph/trailmixes/agile

**Comment by Julian88Tex** [comment]
@mersine how is this one going? if you've finished feel free to add a comment and update this issue's status

**Comment by rodney-zhu** [comment]
The link is broken.

**Comment by rodney-zhu** [comment]
You unlocked it, thanks for making it public. I will complete the two badges this week.  @Julian88Tex

**Comment by Julian88Tex** [comment]
@Rodney-Zhu my pleasure glad it works now. Lmk when you finish.

**Comment by rodney-zhu** [comment]
@Julian88Tex Done. I'm ready to scrum.

**Comment by Julian88Tex** [comment]
@Rodney-Zhu great!
