### ISSUE TITLE
Signup for Loving-Houston Github Org

### ISSUE THREAD

**Issue by Julian88Tex** [lovinghouston/lwcgoogleplacesbutton#17]
@sungysang @mersine realized that we can create an organization so that we can manage our repos better, so please sign up for email that should have been sent to be part of it

**Comment by Julian88Tex** [comment]
@sungysang can you also transfer this repo to that org: https://help.github.jp/enterprise/2.11/user/articles/transferring-a-repository-owned-by-your-personal-account/

**Comment by Julian88Tex** [comment]
@BrandonWilliamBridges added you to this one too

**Comment by sungysang** [comment]
Repo has been transferred to Loving-Houston
