### ISSUE TITLE
Create a Button on Account which Triggers GooglePlaces.searchPlace Class and Sends Current Accounts ID

### ISSUE THREAD

**Issue by Julian88Tex** [lovinghouston/lwcgoogleplacesbutton#23]
As a nonprofit admin at Loving Houston, I would like to click a button on a School Account and Church Accounts near that school will be created along with related CSP records.

ACs

Given I am viewing an Account
When I go to add a button on to the layout
Then I see "Find Churches" as a button to add to the layout
And I can add the button to the layout

Given I am viewing a School Account
And the School has a Billing Zip
And the School has a BIlling Country
When I click the "Find Churches" button
Then 5 Church Accounts near the School are created
And 5 CSP "Potential" Records are Created

Given I am viewing a School Account
And the School does not have a Billing Zip
And the School has a BIlling Country
When I click the "Find Churches" button
Then an error shows on Account record:  "Account does not have a Zip Code and Country."

Given I am viewing a Church Account
And the Church has a Billing Zip
And the Church has a BIlling Country
When I click the "Find Churches" button
Then an error shows on Account record:  "Account is not a School."

Note: If error cannot be displayed, then it is written to debug logs. [To Be Determined by @sungysang, please let @Rodney-Zhu  know]

**Comment by sungysang** [comment]
@Julian88Tex were you able to confirm if this can pass in the longitude/latitude? Or can it only send in record Ids?

**Comment by Julian88Tex** [comment]
@sungysang I haven't verified that however, I don't see why you can't do all 3. That being said, the reason for this ticket is so that the ID is available for time of CSP creation since they will need to be related to the School ID which it's passed.

**Comment by sungysang** [comment]
"You can create an Apex class with an @InvocableMethod (https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_classes_annotation_InvocableMethod.htm) and call it from inside a flow. You can then link to that flow using an action button. I would recommend that approach over a VF page."

**Comment by Julian88Tex** [comment]
This has been completed. Great job @sungysang !
