### ISSUE TITLE
All DML Should Fail for Errors [no partial record creation]

### ISSUE THREAD

**Issue by Julian88Tex** [lovinghouston/lwcgoogleplacesbutton#28]
<img width="1158" alt="Screenshot 2020-02-11 23 17 54" src="https://user-images.githubusercontent.com/459099/74311868-441b7400-4d25-11ea-925f-b02bf506ad09.png">
<img width="311" alt="Screenshot 2020-02-11 23 17 48" src="https://user-images.githubusercontent.com/459099/74311873-467dce00-4d25-11ea-9a40-405ecd271706.png">

**Comment by sungysang** [comment]
@Julian88Tex This is if the button is called from a church rather than a school, the code will attempt to insert a church into the School_Account lookup field which has validation against church record types. One way to bypass this could be to not have the component display on church record types.

**Comment by sungysang** [comment]
The code should check if CSP record creation or Account creation is successful.

**Comment by Julian88Tex** [comment]
@sungysang you're saying that's how it does work or how it should work?

**Comment by Julian88Tex** [comment]
Closing since this is an old bug but I think I've found a new version of it #44
