### ISSUE TITLE
Create School Accounts based on Distance

### ISSUE THREAD

**Issue by Julian88Tex** [lovinghouston/lwcgoogleplacesbutton#29]
As a developer/tester, when I run the GooglePlaces.searchPlace method, I would like Accounts to be created based on closest to furthest.

**ACs**

Given a School Account exists
And Church Account has Zip & Country
When Google Places class is run correctly using School Account's ID
Then 5 Church Accounts that are created are from closest to furthest based on their Billing Address

Note: For MVP, no need worry about if two churches are the same distance from the school.

**Comment by sungysang** [comment]
https://developers.google.com/places/web-service/search

_"rankby — Specifies the order in which results are listed."_

**Comment by sungysang** [comment]
_"Note that radius must not be included if rankby=distance"_

**Comment by Julian88Tex** [comment]
This has been completed. Great job @sungysang !
