### ISSUE TITLE
Display CSP records in Distance Flow

### ISSUE THREAD

**Issue by Julian88Tex** [lovinghouston/lwcgoogleplacesbutton#3]
As an admin, I want to get a list of potential Accounts in a flow as CSP records based on a given Account when triggered by a flow.

ACs

Given the flow from issue #2 is run
And an Account ID is provided by user in flow
And Account is Type = School
When clicking to next page in flow
Then a list of 100 or less records are displayed on flow screen but not created [aka are not given Salesforce IDs]
And records are selectable
And the matched Account name is displayed
And all Accounts are churches
And distance between provided between Account and other matched Account is displayed [in miles]
And all records are sorted from closest to furthest

Given the flow from issue #2 is run
And an Account ID is provided by user in flow
And Account is Type = Church
When clicking to next page in flow
Then a list of 100 or less records are displayed on flow screen but not created [aka are not given Salesforce IDs]
And records are selectable
And the matched Account name is displayed
And all Accounts are schooles
And distance between provided between Account and other matched Account is displayed [in miles]
And all records are sorted from closest to furthest

Given flow from issue #2 is run
And no Account ID is provided by user in flow
When clicking to next page on flow screen
Flow shows an error on screen "Please provide an account ID." [can be done through required fields]

Given flow from issue #2 is run
When the page loads
And no record are found
Then a message will be displayed "No potential CSP records have been found."

**Comment by sungysang** [comment]
@Julian88Tex The biggest hurdle I'm running into is displaying the apex method's return records in a flow screen as selectable records. This does not seem to be possible with the base set of flow components. I've researched a potential component solution [here](https://unofficialsf.com/datatable/) but this will require mydomain to be set up for LH's Sandbox.

Also FYI I hooked up the Apex method to the "Find Close Accounts" Flow in the Sandbox if u wanna take a look and test it out there

**Comment by Julian88Tex** [comment]
@sungysang Okay thanks for the update. Feel free to enable mydomain in the sandbox. If our end solution requires it, I doubt that will be an issue to set up for them however less than ideal because we'll likely need to evaluate a few different things before enabling it. In particular, I would want to make sure it doesn't break the website map integration.

**Comment by Julian88Tex** [comment]
@sungysang will be closing this out due to an architecture change to use Google Nearby Places API

sorry 😿
