### ISSUE TITLE
[SPIKE] Figure out what information can be added to Church Account upon creation

### ISSUE THREAD

**Issue by Julian88Tex** [lovinghouston/lwcgoogleplacesbutton#36]
As an admin at LH, I'd like to have as much information as possible on a church record so that I can validate the church is active and has resources for a healthy partnership.

- evaluate all fields returned from Google Places API and see which ones can be added to fields on an Account record
- evaluate if any fields need to be created
- consider using Places Detail search: https://maps.googleapis.com/maps/api/place/details/json?place_id=ChIJIfSCtuz424ARkm7VXC1Io64&fields=name,rating,price_level,review,user_ratings_total,formatted_phone_number,international_phone_number,opening_hours,website,address_component,adr_address,formatted_address,geometry,icon,name,permanently_closed,photo,place_id,plus_code,type,url,utc_offset,vicinity&key=[APIkey]
- if easier, okay with adding any information that doesn't have a logical place to a long text metadata/description field
-nth: if there is somewhere logical (maybe attachments) to place and retrieve any images returned

Finished Product: Comments on this spike which list all information and what fields to place it in along with any recommendations of where to place other data.

**Comment by sungysang** [comment]
List of currently returned fields:
 formatted_address
geometry
name
opening_hours
photos
rating

In order to implement, a separate Details call will have to be made for each textSearch result: https://developers.google.com/places/web-service/details
and then inserted back into the results

**Comment by Julian88Tex** [comment]
note: fields should not fill in or overwrite any existing data for now; if account already exists, do not update any fields

nth details fields:

- formatted_phone_number -> Phone [standard field]
- url -> Google Maps Listing [new field]
- website -> Website
- entire response of call -> Google API Place Details Response [new field]

other data:
- photos -> saved as files
- icon -> saved as logo [may need to enable feature: https://help.salesforce.com/articleView?id=account_logos_enable.htm&type=5]

**Comment by Julian88Tex** [comment]
@sungysang in addition to what you already have on LWC for displaying results I think it would also be nice to have these fields assuming displayed:

website (clickable) & url (clickable) & distance

sorted by distance from closest to furthest

**Comment by sungysang** [comment]
@Julian88Tex Could you close this one once you create the new issue for list of details?

**Comment by Julian88Tex** [comment]
Yup, closing since this ticket lead to creation of #51
