### ISSUE TITLE
Unit Tests for All Existing Code [Dependent on Duplicates & Fields tickets]

### ISSUE THREAD

**Issue by Julian88Tex** [lovinghouston/lwcgoogleplacesbutton#37]
As a developer/QA on this project, I would like to be able to deploy our code to LH's production org.

ACs

Given an LH dev Sandbox org
And "Find Churches" button project code is pushed to Sandbox
When I click "Run All" unite tests
Then All unit tests run
And All unit tests pass
And Code Coverage is 85% or more

Given LH's production org
and an inbound change set is created from an LH dev Sandbox
And Sandbox contains the newest "Find Churches" button project code
When the change set is deployed
Then the change set deployment passes
And there are no errors
And LH's production org contains the newest "Find Churches" button project code

**Comment by sungysang** [comment]
https://salesforce.stackexchange.com/questions/139235/how-to-create-mock-class-for-multiple-callouts-in-single-class

**Comment by Julian88Tex** [comment]
Good job. Confirmed unit tests are above 85% and that all tests pass:

<img width="415" alt="Screenshot 2020-04-07 21 12 25" src="https://user-images.githubusercontent.com/459099/78743842-b74ff980-7914-11ea-8f9d-1a128c2fe380.png">


Additionally, I created a Github action that runs these tests on every push.
