### ISSUE TITLE
Change "Find Churches" button name to "Find Closest Churches"

### ISSUE THREAD

**Issue by Julian88Tex** [lovinghouston/lwcgoogleplacesbutton#39]
As an admin, I want to know that the "Find Churches" button always finds more churches and is reusable.

Given a school record
When I navigate to the school record
Then I see a button named "Find More Churches"
and a button "Find Closest Churches" doesn't exist
and I can click the button and it runs previously created functionality

**Comment by sungysang** [comment]
![Screen Shot 2020-03-16 at 12 24 15 AM](https://user-images.githubusercontent.com/53227499/76732669-7fda9c80-671c-11ea-9abc-df18da13c8d8.png)

**Comment by Julian88Tex** [comment]
This has been completed. Great job @sungysang !
