### ISSUE TITLE
Distance Field shows Incorrect Value on Data Table

### ISSUE THREAD

**Issue by sungysang** [lovinghouston/lwcgoogleplacesbutton#51]
When I click on the button, the distance number shows an impossibly large value. After some time, it seems to refresh and show the correct value when I look at the CSP record.

![Screen Shot 2020-03-19 at 11 36 47 AM](https://user-images.githubusercontent.com/53227499/77102469-1c7b9380-69d6-11ea-87d6-4ff64b65e7d8.png)

**Comment by sungysang** [comment]
The field may need some time to calculate, so I could add some sort of wait timer before it displays

**Comment by Julian88Tex** [comment]
@sungysang, for now, let's just remove distance from data table after clicking button
