### ISSUE TITLE
[Blocked] Invalidate Google API Key that is Public

### ISSUE THREAD

**Issue by Julian88Tex** [lovinghouston/lwcgoogleplacesbutton#57]
- delete old Google API Key used here: https://github.com/lovinghouston/lwcgoogleplacesbutton/blob/master/force-app/main/default/classes/GooglePlacesUtility.cls#L86

**Comment by sungysang** [comment]
@Julian88Tex  if you can let me know the new API Key I can update the metadata

**Comment by Julian88Tex** [comment]
> @Julian88Tex if you can let me know the new API Key I can update the metadata

@sungysang it's in the same LastPass secure note

**Comment by sungysang** [comment]
@Julian88Tex It's updated so feel free to invalidate the old one

**Comment by Julian88Tex** [comment]
@sungysang thanks I've deleted it.
