### ISSUE TITLE
[BUG]: If no churches can be created from first call, null object error is thrown

### ISSUE THREAD

**Issue by sungysang** [lovinghouston/lwcgoogleplacesbutton#60]
Problem: On certain occasions, Google API will return places that all do not contain a valid address. If this occurs, no raw churches are created and so a null List is thrown around in the code, causing a null object error.

Solutions:
1. Throw an exception if no churches were created from the call so the null object error is not thrown.
2. Allow partial addresses to be accepted when creating new churches.

@Julian88Tex This error is shown in the component currently so users won't run into an infinite loading icon, but up to you if you want to include a fix before MVP and which solution you'd like to go towards. Step 1 would basically just be throwing a custom exception ("Google Data returned invalid results") instead of the null object error.

![Screen Shot 2020-04-02 at 7 12 09 PM](https://user-images.githubusercontent.com/53227499/78316964-e120af00-7515-11ea-97b0-b3b0388b99cd.png)

**Comment by Julian88Tex** [comment]
@sungysang thanks for creating this. I'm not adding this to MVP since it is low risk for data quality.

**Comment by sungysang** [comment]
@Julian88Tex can this be closed?

**Comment by Julian88Tex** [comment]
@sungysang have we validated it is no longer occuring? I can say I haven't.

**Comment by sungysang** [comment]
@Julian88Tex have tested this on my own and there is a unit test that checks for this

**Comment by Julian88Tex** [comment]
@sungysang cool can you link to unit test? I'll verify and close.

**Comment by sungysang** [comment]
https://github.com/lovinghouston/lwcgoogleplacesbutton/blob/master/force-app/main/default/classes/GooglePlaces_TEST.cls#L101

**Comment by Julian88Tex** [comment]
@sungysang looks good thanks will close!
