### ISSUE TITLE
[BUG]: Attempt to de-reference null object if an Account that should be a Church does not have correct Type

### ISSUE THREAD

**Issue by sungysang** [lovinghouston/lwcgoogleplacesbutton#62]
Example: https://lovinghouston--partial.lightning.force.com/lightning/r/Account/0011N000018j3uIQAQ/view

Solution: Remove Type clause in SOQL query that relies on it

**Comment by rodney-zhu** [comment]
@sungysang this has passed. @Julian88Tex will add a video of the work we did together. [https://docs.google.com/document/d/1GeXbOqHqqUDywF2JyN6cx-fiVbHIbEU1t0pkRHcEU78/edit](https://docs.google.com/document/d/1GeXbOqHqqUDywF2JyN6cx-fiVbHIbEU1t0pkRHcEU78/edit)

**Comment by Julian88Tex** [comment]
@Rodney-Zhu great job! Here's our recording which I've shared with @sungysang and @jonatng as well in case they are curious about testing.

**Comment by Julian88Tex** [comment]
Great job on dev @sungysang and great job on testing @Rodney-Zhu !

Closing this out since it is complete.
