### ISSUE TITLE
Throw new Exception if initial Status Code is bad

### ISSUE THREAD

**Issue by sungysang** [lovinghouston/lwcgoogleplacesbutton#67]
Google does not populate the default status code on the HTTPResponse so response.getStatusCode() will always be 200 even if an error message is inside it. For situations where Salesforce has issues getting back a response or sending a request, instead of returning null if the status != 200, an exception should be thrown to the backend and frontend that describes the issue.

**Comment by sungysang** [comment]
@Julian88Tex this can be closed unless you want testing on it, although it may be tough to test since I'm not sure how to reproduce an API error in Salesforce

**Comment by Julian88Tex** [comment]
@sungysang I consider testing of #57 as a valid test of this issue and will close. Thanks.
