### ISSUE TITLE
[BUG] Attempt to de-reference null object if beginning Account Type is null

### ISSUE THREAD

**Issue by sungysang** [lovinghouston/lwcgoogleplacesbutton#73]
Steps to reproduce:
1. Go to Account with blank Type field.
2. Press button.

Attempt to de-reference null object will be thrown.

Fix: Perform a check on the Type field before validating its value and throw a more helpful error message if it is null

Recommend checking various Type values as well as blank while testing.

**Comment by sungysang** [comment]
@Rodney-Zhu  can you please test this?

**Comment by rodney-zhu** [comment]
@sungysang Test Passes for any Account that is not School. Error message is, "Invalid Account Type. Type needs to be school."

https://docs.google.com/document/d/1RxL7qWxqFB1iLfCXqiY_0Peu9NUZ7-ufXXkPaT3IEgo/edit?usp=sharing

**Comment by Julian88Tex** [comment]
Great job on dev @sungysang and great job on testing @Rodney-Zhu !

Closing this out since it is complete.
