### ISSUE TITLE
Update Documentation to include FAQ & Google Duplicate Results Section Based on Email

### ISSUE THREAD

**Issue by Julian88Tex** [lovinghouston/lwcgoogleplacesbutton#90]
After early UAT, LH wrote back with some questions about Google Duplicates and other interesting situations. It would be great to add this to our google doc file.

I recommend keeping this in the same document and not creating a separate one for easy of access.

**Comment by jonatng** [comment]
@Julian88Tex documentation is updated. If you feel more should be added, LMK

**Comment by Julian88Tex** [comment]
@jonatng nice! added some suggestions to FAQ

**Comment by Julian88Tex** [comment]
Good job thanks @jonatng
