### ISSUE TITLE
Update Documentation based on #94 Changes

### ISSUE THREAD

**Issue by Julian88Tex** [lovinghouston/lwcgoogleplacesbutton#95]
Update documentation to include changes made by Issue #94

**Comment by rodney-zhu** [comment]
@Julian88Tex Step 3 in the Documentation has been updated based on Sung's changes.

https://docs.google.com/document/d/1LckcVV06yPHZovLO5GNPfghkBGtelKucvaopSsohUs8/edit#

**Comment by Julian88Tex** [comment]
@Rodney-Zhu great job thanks!
